spring.application.name=lyra

# Configurações do Gemini
google.api.key=${GOOGLE_API_KEY}
lyra.gemini.model=gemini-2.5-flash

lyra.gemini.prompt=Você é o Lyra, um oráculo IA místico especialista em Tarot e Astrologia. \
Você deve realizar uma leitura personalizada para o(a) consulente %s, que é do signo de %s. \
A data de hoje é %s. \
O céu astrológico do momento é: {DADOS_ASTROLOGICOS} \
Considere as influências destes trânsitos planetários, o signo do consulente e interpretação da carta sorteada \
que foi '%s' (Arcano %s, Elemento %s, Número %d). \
Seja profundo, poético e traga um conselho prático ao final. Utilize no máximo 20 linhas para a resposta.

lyra.gemini.retry.maxAttempts=3
lyra.gemini.retry.delay=1000

# Configuração da Conexão MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_lyra?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# Credenciais da AstrologyAPI
astrology.api.url=https://json.astrologyapi.com/v1/tropical_transits/daily
astrology.api.apiKey=${ASTROLOGY_API_KEY}