INSERT IGNORE INTO tb_cartas (id, nome, numero, elemento, imagem_url, arcano, significado_geral) VALUES 
-- ARCANOS MAIORES
(1, 'O Louco', 0, 'Ar', '-', 'MAIOR', 'Novos começos, otimismo, liberdade e saltos de fé.'),
(2, 'O Mago', 1, 'Ar', '-', 'MAIOR', 'Manifestação, recursos, poder pessoal e ação consciente.'),
(3, 'A Sacerdotisa', 2, 'Água', '-', 'MAIOR', 'Intuição, mistério, subconsciente e sabedoria passiva.'),
(4, 'A Imperatriz', 3, 'Terra', '-', 'MAIOR', 'Feminilidade, fertilidade, natureza e abundância.'),
(5, 'O Imperador', 4, 'Fogo', '-', 'MAIOR', 'Autoridade, estrutura, estabilidade e proteção.'),
(6, 'O Hierofante', 5, 'Terra', '-', 'MAIOR', 'Tradição, conformidade, mentoria e valores espirituais.'),
(7, 'Os Enamorados', 6, 'Ar', '-', 'MAIOR', 'Amor, harmonia, relacionamentos e escolhas difíceis.'),
(8, 'O Carro', 7, 'Água', '-', 'MAIOR', 'Controle, força de vontade, vitória e determinação.'),
(9, 'A Força', 8, 'Fogo', '-', 'MAIOR', 'Coragem, influência suave, compaixão e força interior.'),
(10, 'O Eremita', 9, 'Terra', '-', 'MAIOR', 'Introspecção, busca pela verdade, solidão e orientação interna.'),
(11, 'A Roda da Fortuna', 10, 'Fogo', '-', 'MAIOR', 'Mudança, ciclos, destino, sorte e reviravoltas.'),
(12, 'A Justiça', 11, 'Ar', '-', 'MAIOR', 'Equilíbrio, justiça, verdade e causa e efeito.'),
(13, 'O Pendurado', 12, 'Água', '-', 'MAIOR', 'Pausa, rendição, novas perspectivas e sacrifício.'),
(14, 'A Morte', 13, 'Água', '-', 'MAIOR', 'Fim de um ciclo, transformação profunda e transição.'),
(15, 'A Temperança', 14, 'Fogo', '-', 'MAIOR', 'Equilíbrio, moderação, paciência e propósito.'),
(16, 'O Diabo', 15, 'Terra', '-', 'MAIOR', 'Sombra, apego, vício, sexualidade e materialismo.'),
(17, 'A Torre', 16, 'Fogo', '-', 'MAIOR', 'Mudança súbita, desastre, revelação e libertação.'),
(18, 'A Estrela', 17, 'Ar', '-', 'MAIOR', 'Esperança, fé, renovação e espiritualidade.'),
(19, 'A Lua', 18, 'Água', '-', 'MAIOR', 'Ilusão, medo, ansiedade e intuição aguçada.'),
(20, 'O Sol', 19, 'Fogo', '-', 'MAIOR', 'Positividade, diversão, calor, sucesso e vitalidade.'),
(21, 'O Julgamento', 20, 'Fogo', '-', 'MAIOR', 'Renascimento, chamado interno e perdão.'),
(22, 'O Mundo', 21, 'Terra', '-', 'MAIOR', 'Conclusão, integração, realização e viagem.'),
-- ARCANOS MENORES - NAIPE DE PAUS (FOGO)
(23, 'Ás de Paus', 1, 'Fogo', '-', 'MENOR', 'Inspiração, novas oportunidades, crescimento, energia criativa e potencial.'),
(24, 'Dois de Paus', 2, 'Fogo', '-', 'MENOR', 'Planejamento futuro, progresso, decisões, descobertas e sair da zona de conforto.'),
(25, 'Três de Paus', 3, 'Fogo', '-', 'MENOR', 'Preparação, visão de longo prazo, expansão, exploração e liderança.'),
(26, 'Quatro de Paus', 4, 'Fogo', '-', 'MENOR', 'Celebração, harmonia, casamento, lar, segurança e conquistas iniciais.'),
(27, 'Cinco de Paus', 5, 'Fogo', '-', 'MENOR', 'Conflito, desentendimentos, competição, tensão e diversidade de opiniões.'),
(28, 'Seis de Paus', 6, 'Fogo', '-', 'MENOR', 'Vitória, sucesso, reconhecimento público, orgulho e autoconfiança.'),
(29, 'Sete de Paus', 7, 'Fogo', '-', 'MENOR', 'Desafio, perseverança, defesa de território e manutenção do controle.'),
(30, 'Oito de Paus', 8, 'Fogo', '-', 'MENOR', 'Movimento rápido, ação, notícias, mudanças repentinas e viagens.'),
(31, 'Nove de Paus', 9, 'Fogo', '-', 'MENOR', 'Resiliência, coragem, persistência, testes de fé e limites estabelecidos.'),
(32, 'Dez de Paus', 10, 'Fogo', '-', 'MENOR', 'Fardo, responsabilidade extra, trabalho duro, estresse e exaustão.'),
(33, 'Pajem de Paus', 11, 'Fogo', '-', 'MENOR', 'Entusiasmo, exploração, descoberta, espírito livre e novas ideias.'),
(34, 'Cavaleiro de Paus', 12, 'Fogo', '-', 'MENOR', 'Energia, paixão, impulsividade, aventura e ação rápida.'),
(35, 'Rainha de Paus', 13, 'Fogo', '-', 'MENOR', 'Coragem, confiança, independência, determinação e calor humano.'),
(36, 'Rei de Paus', 14, 'Fogo', '-', 'MENOR', 'Liderança, visão, empreendedorismo, honra e carisma.'),
-- NAIPE DE COPAS (ÁGUA)
(37, 'Ás de Copas', 1, 'Água', '-', 'MENOR', 'Amor, novas emoções, intuição, compaixão e fluidez espiritual.'),
(38, 'Dois de Copas', 2, 'Água', '-', 'MENOR', 'Parceria, união, amor mútuo, atração e relacionamentos harmoniosos.'),
(39, 'Três de Copas', 3, 'Água', '-', 'MENOR', 'Amizade, celebração, colaboração, comunidade e encontros felizes.'),
(40, 'Quatro de Copas', 4, 'Água', '-', 'MENOR', 'Meditação, contemplação, apatia, reavaliação e oportunidades ignoradas.'),
(41, 'Cinco de Copas', 5, 'Água', '-', 'MENOR', 'Perda, luto, decepção, arrependimento e foco no passado.'),
(42, 'Seis de Copas', 6, 'Água', '-', 'MENOR', 'Nostalgia, memórias de infância, inocência, alegria simples e reencontros.'),
(43, 'Sete de Copas', 7, 'Água', '-', 'MENOR', 'Opções, ilusões, fantasia, escolhas múltiplas e idealização.'),
(44, 'Oito de Copas', 8, 'Água', '-', 'MENOR', 'Desapego, afastamento, busca espiritual, transição e abandono do que não serve mais.'),
(45, 'Nove de Copas', 9, 'Água', '-', 'MENOR', 'Satisfação, desejos realizados, conforto, gratidão e contentamento.'),
(46, 'Dez de Copas', 10, 'Água', '-', 'MENOR', 'Felicidade divina, relacionamentos felizes, harmonia familiar e alinhamento.'),
(47, 'Pajem de Copas', 11, 'Água', '-', 'MENOR', 'Mensagens criativas, intuição, sincronismo, amor idealista e sensibilidade.'),
(48, 'Cavaleiro de Copas', 12, 'Água', '-', 'MENOR', 'Romance, charme, imaginação, idealismo e convites amorosos.'),
(49, 'Rainha de Copas', 13, 'Água', '-', 'MENOR', 'Compaixão, cuidado, estabilidade emocional, intuição e empatia profunda.'),
(50, 'Rei de Copas', 14, 'Água', '-', 'MENOR', 'Equilíbrio emocional, controle, diplomacia, sabedoria e tolerância.'),
-- NAIPE DE ESPADAS (AR)
(51, 'Ás de Espadas', 1, 'Ar', '-', 'MENOR', 'Clareza mental, verdade, novas ideias, visão e cortes necessários.'),
(52, 'Dois de Espadas', 2, 'Ar', '-', 'MENOR', 'Impasse, escolhas difíceis, negação, bloqueio e evitação de fatos.'),
(53, 'Três de Espadas', 3, 'Ar', '-', 'MENOR', 'Desgosto, tristeza, luto, separação e dor emocional.'),
(54, 'Quatro de Espadas', 4, 'Ar', '-', 'MENOR', 'Descanso, recuperação, contemplação, pausa e preparação mental.'),
(55, 'Cinco de Espadas', 5, 'Ar', '-', 'MENOR', 'Conflito, tensão, perda, derrota, traição e vitórias vazias.'),
(56, 'Seis de Espadas', 6, 'Ar', '-', 'MENOR', 'Transição, deixando bagagem para trás, cura, movimento e águas mais calmas.'),
(57, 'Sete de Espadas', 7, 'Ar', '-', 'MENOR', 'Estratégia, engano, furtividade, táticas ocultas e independência.'),
(58, 'Oito de Espadas', 8, 'Ar', '-', 'MENOR', 'Prisão mental, impotência, vitimização, restrição e crenças limitantes.'),
(59, 'Nove de Espadas', 9, 'Ar', '-', 'MENOR', 'Ansiedade, pesadelos, preocupação, medo e angústia mental.'),
(60, 'Dez de Espadas', 10, 'Ar', '-', 'MENOR', 'Fim doloroso, traição, exaustão, encerramento de ciclo e fundo do poço.'),
(61, 'Pajem de Espadas', 11, 'Ar', '-', 'MENOR', 'Curiosidade, sede de conhecimento, novas formas de comunicação e mente ágil.'),
(62, 'Cavaleiro de Espadas', 12, 'Ar', '-', 'MENOR', 'Ação rápida, ambição, determinação, impulsividade mental e assertividade.'),
(63, 'Rainha de Espadas', 13, 'Ar', '-', 'MENOR', 'Comunicação clara, independência, julgamento imparcial, limites e objetividade.'),
(64, 'Rei de Espadas', 14, 'Ar', '-', 'MENOR', 'Poder intelectual, autoridade, clareza, verdade objetiva e disciplina mental.'),
-- NAIPE DE OUROS (TERRA)
(65, 'Ás de Ouros', 1, 'Terra', '-', 'MENOR', 'Novas oportunidades financeiras, manifestação, abundância e prosperidade material.'),
(66, 'Dois de Ouros', 2, 'Terra', '-', 'MENOR', 'Equilíbrio, adaptação, gerenciamento de tempo, recursos e flexibilidade.'),
(67, 'Três de Ouros', 3, 'Terra', '-', 'MENOR', 'Trabalho em equipe, colaboração, aprendizado, habilidade e construção conjunta.'),
(68, 'Quatro de Ouros', 4, 'Terra', '-', 'MENOR', 'Controle, estabilidade, segurança, apego material e economia.'),
(69, 'Cinco de Ouros', 5, 'Terra', '-', 'MENOR', 'Dificuldade financeira, isolamento, perda, pobreza e abandono.'),
(70, 'Seis de Ouros', 6, 'Terra', '-', 'MENOR', 'Generosidade, caridade, compartilhar riqueza, receber ajuda e fluxo de prosperidade.'),
(71, 'Sete de Ouros', 7, 'Terra', '-', 'MENOR', 'Visão de longo prazo, paciência, investimento, colheita e avaliação de progresso.'),
(72, 'Oito de Ouros', 8, 'Terra', '-', 'MENOR', 'Mestria, desenvolvimento de habilidades, dedicação, detalhismo e trabalho focado.'),
(73, 'Nove de Ouros', 9, 'Terra', '-', 'MENOR', 'Independência financeira, luxo, autossuficiência, recompensa e conforto.'),
(74, 'Dez de Ouros', 10, 'Terra', '-', 'MENOR', 'Riqueza familiar, legado, estabilidade a longo prazo, tradição e herança.'),
(75, 'Pajem de Ouros', 11, 'Terra', '-', 'MENOR', 'Manifestação prática, novas habilidades, foco, estudo e dedicação a um projeto.'),
(76, 'Cavaleiro de Ouros', 12, 'Terra', '-', 'MENOR', 'Trabalho duro, produtividade, rotina, conservadorismo e método.'),
(77, 'Rainha de Ouros', 13, 'Terra', '-', 'MENOR', 'Cuidado, senso prático, provisão, segurança material, nutrição e riqueza interior.'),
(78, 'Rei de Ouros', 14, 'Terra', '-', 'MENOR', 'Abundância, poder financeiro, segurança, sucesso nos negócios e solidez.');